# Generated by Django 5.1.4 on 2024-12-04 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='contents',
            field=models.ManyToManyField(blank=True, related_name='subjects', to='app.content'),
        ),
        migrations.AlterField(
            model_name='content',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_subjects', to='app.subject'),
        ),
    ]
